// User
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_EDIT = "USER_EDIT";
// Dialogs
export const DIALOGS_GET = "DIALOGS_GET";
export const DIALOGS_ADD = "DIALOGS_ADD";
export const DIALOGS_ADD_MESSAGE = "DIALOGS_ADD_MESSAGE";
export const DIALOGS_SUCCESS_MESSAGE = "DIALOGS_SUCCESS_MESSAGE";
export const DIALOGS_ERROR_MESSAGE = "DIALOGS_ERROR_MESSAGE";
export const DIALOGS_READ_MESSAGES = "DIALOGS_READ_MESSAGES";
export const DIALOGS_LOAD = "DIALOGS_LOAD";
export const DIALOGS_SET_TYPER = "DIALOGS_SET_TYPER";
export const DIALOGS_REMOVE_TYPER = "DIALOGS_REMOVE_TYPER";
export const DIALOGS_SET_LOADING = "DIALOGS_SET_LOADING";
export const DIALOGS_LOAD_MESSAGES = "DIALOGS_LOAD_MESSAGES";
export const DIALOGS_UPDATE_ONLINE = "DIALOGS_UPDATE_ONLINE";
export const DIALOGS_SET_FORWARD = "DIALOGS_SET_FORWARD";
export const DIALOGS_PRELOAD = "DIALOGS_PRELOAD";
export const DIALOGS_DELETE_MESSAGE = "DIALOGS_DELETE_MESSAGE";

// Users
export const USERS_GET = "USERS_GET";
export const USERS_ADD = "USERS_ADD";
